-- AthenaHealth EHR Tables
-- Tables for patient data, encounters, and appointments from AthenaHealth system

USE SCHEMA AHF_HEALTHCARE_DEMO.ATHENA_EHR;

-- Patients table from AthenaHealth
CREATE OR REPLACE TABLE PATIENTS (
    PATIENT_ID VARCHAR(10) PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GENDER VARCHAR(1) CHECK (GENDER IN ('M', 'F')),
    PHONE VARCHAR(12),
    EMAIL VARCHAR(100),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    STATE VARCHAR(2),
    ZIP_CODE VARCHAR(10),
    INSURANCE_ID VARCHAR(20),
    PRIMARY_CARE_PROVIDER VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Patient encounters table
CREATE OR REPLACE TABLE ENCOUNTERS (
    ENCOUNTER_ID VARCHAR(10) PRIMARY KEY,
    PATIENT_ID VARCHAR(10) NOT NULL,
    ENCOUNTER_DATE DATE NOT NULL,
    ENCOUNTER_TYPE VARCHAR(50) NOT NULL,
    PROVIDER_NAME VARCHAR(100) NOT NULL,
    CHIEF_COMPLAINT VARCHAR(500),
    DIAGNOSIS_CODE VARCHAR(20),
    DIAGNOSIS_DESCRIPTION VARCHAR(200),
    CLINICAL_NOTES TEXT,
    VISIT_DURATION_MINUTES INTEGER,
    FOLLOW_UP_NEEDED BOOLEAN DEFAULT FALSE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
);

-- Appointments table
CREATE OR REPLACE TABLE APPOINTMENTS (
    APPOINTMENT_ID VARCHAR(10) PRIMARY KEY,
    PATIENT_ID VARCHAR(10) NOT NULL,
    APPOINTMENT_DATE DATE NOT NULL,
    APPOINTMENT_TIME TIME NOT NULL,
    APPOINTMENT_TYPE VARCHAR(50) NOT NULL,
    PROVIDER_NAME VARCHAR(100) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Scheduled' CHECK (STATUS IN ('Scheduled', 'Completed', 'Cancelled', 'No Show')),
    REASON_FOR_VISIT VARCHAR(500),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
);

-- Snowflake uses clustering keys instead of traditional indexes for performance
-- These can be added later if needed based on query patterns:
-- ALTER TABLE ENCOUNTERS CLUSTER BY (ENCOUNTER_DATE, PATIENT_ID);
-- ALTER TABLE APPOINTMENTS CLUSTER BY (APPOINTMENT_DATE, PATIENT_ID);

COMMENT = 'AthenaHealth EHR tables created successfully';
