-- McKesson Pharmacy Tables
-- Tables for prescription data and pharmacy locations from McKesson system

USE SCHEMA AHF_HEALTHCARE_DEMO.MCKESSON_PHARMACY;

-- Pharmacy locations table
CREATE OR REPLACE TABLE PHARMACY_LOCATIONS (
    PHARMACY_ID VARCHAR(10) PRIMARY KEY,
    PHARMACY_NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    PHONE VARCHAR(12),
    MANAGER_NAME VARCHAR(100),
    HOURS_OF_OPERATION VARCHAR(200),
    SERVICES_OFFERED TEXT,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Prescriptions table
CREATE OR REPLACE TABLE PRESCRIPTIONS (
    PRESCRIPTION_ID VARCHAR(10) PRIMARY KEY,
    PATIENT_ID VARCHAR(10) NOT NULL,
    PRESCRIBER_NAME VARCHAR(100) NOT NULL,
    MEDICATION_NAME VARCHAR(100) NOT NULL,
    MEDICATION_STRENGTH VARCHAR(20),
    QUANTITY INTEGER NOT NULL,
    DAYS_SUPPLY INTEGER NOT NULL,
    PRESCRIBED_DATE DATE NOT NULL,
    FILLED_DATE DATE,
    PICKUP_DATE DATE,
    PICKUP_STATUS VARCHAR(20) DEFAULT 'Not Picked Up' CHECK (PICKUP_STATUS IN ('Picked Up', 'Not Picked Up', 'Partially Picked Up')),
    PHARMACY_LOCATION VARCHAR(100),
    REFILLS_REMAINING INTEGER DEFAULT 0,
    COST DECIMAL(10,2),
    INSURANCE_COPAY DECIMAL(10,2),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Snowflake uses clustering keys instead of traditional indexes for performance
-- These can be added later if needed based on query patterns:
-- ALTER TABLE PRESCRIPTIONS CLUSTER BY (PRESCRIBED_DATE, PATIENT_ID);

COMMENT = 'McKesson Pharmacy tables created successfully';
